export const workbookSchema = {
 type:'object', additionalProperties:false,
 properties:{
  metadata:{type:'object',additionalProperties:false,properties:{lessonTitle:{type:'string'},subject:{type:'string'},learningLevel:{type:'string'},learningMethod:{type:'string'},duration:{type:'string'},difficulty:{type:'string'},language:{type:'string',enum:['id','en','ar']},direction:{type:'string',enum:['ltr','rtl']}},required:['lessonTitle','subject','learningLevel','learningMethod','duration','difficulty','language','direction']},
  learningObjectives:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},text:{type:'string'},cognitiveLevel:{type:'string'}},required:['id','text','cognitiveLevel']}},
  learningInstructions:{type:'array',items:{type:'string'}},
  apperception:{type:'object',additionalProperties:false,properties:{title:{type:'string'},content:{type:'string'},studentAction:{type:'string'}},required:['title','content','studentAction']},
  stimulus:{type:'object',additionalProperties:false,properties:{title:{type:'string'},type:{type:'string'},content:{type:'string'}},required:['title','type','content']},
  triggerQuestions:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},question:{type:'string'},purpose:{type:'string'}},required:['id','question','purpose']}},
  materialSnapshot:{type:'object',additionalProperties:false,properties:{title:{type:'string'},content:{type:'string'}},required:['title','content']},
  activities:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},title:{type:'string'},learningStage:{type:'string'},objectiveReference:{type:'array',items:{type:'string'}},instruction:{type:'string'},studentTasks:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},task:{type:'string'},responseType:{type:'string',enum:['short_text','long_text','table','comparison_table','case_analysis','reflection']},responseConfig:{type:'object',additionalProperties:false,properties:{columns:{anyOf:[{type:'array',items:{type:'string'}},{type:'null'}]},rows:{anyOf:[{type:'integer'},{type:'array',items:{type:'string'}},{type:'null'}]},fields:{anyOf:[{type:'array',items:{type:'string'}},{type:'null'}]}},required:['columns','rows','fields']}},required:['id','task','responseType','responseConfig']} }},required:['id','title','learningStage','objectiveReference','instruction','studentTasks']}},
  reflection:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},question:{type:'string'},responseType:{type:'string',enum:['long_text']}},required:['id','question','responseType']}},
  assessment:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},objectiveReference:{type:'array',items:{type:'string'}},question:{type:'string'},type:{type:'string'},cognitiveLevel:{type:'string'},expectedEvidence:{type:'string'}},required:['id','objectiveReference','question','type','cognitiveLevel','expectedEvidence']}},
  rubric:{type:'object',additionalProperties:false,properties:{included:{type:'boolean'},criteria:{type:'array',items:{type:'object',additionalProperties:false,properties:{criterion:{type:'string'},levels:{type:'array',items:{type:'object',additionalProperties:false,properties:{score:{type:'integer'},descriptor:{type:'string'}},required:['score','descriptor']}}},required:['criterion','levels']}}},required:['included','criteria']},
  conclusion:{type:'object',additionalProperties:false,properties:{instruction:{type:'string'}},required:['instruction']}
 },
 required:['metadata','learningObjectives','learningInstructions','apperception','stimulus','triggerQuestions','materialSnapshot','activities','reflection','assessment','rubric','conclusion']
} as const;
